backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'papers'
    label: 'Papers'
    folder: 'content/papers'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Authors', name: 'authors', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'LLL', timeFormat: false, dateFormat: 'YYYY-MM-DD', picker_utc: false }
      - { label: 'PDF Title', name: 'pdf-title', widget: 'string' }
      - { label: 'PDF File', name: 'pdf-file', widget: 'file' }
      - { label: 'DOI', name: 'doi', widget: 'string' }
#     - { label: 'description', name: 'description', widget: 'markdown' }
#     - { label: 'Images', name: 'images', widget: 'list', fields: [{ name: 'path', label: 'Image', widget: 'image'}, { name: 'alt', label: 'Alt', widget: 'string'} ] }
 
